### ISSUE TITLE
It has router, that's not part of SPA?

### ISSUE THREAD

**Issue by set92** [kitwon/vue-mpa#1]
I'm pretty new to the web development world, and I didn't want to do a SPA with Vue JS, but I can't find any tutorial or anything without SPA, and while I searched for it, I was reading and in [one article](https://adamsilver.io/articles/the-disadvantages-of-single-page-applications/) it says that the important thing of a SPA web is that the JS handles the routes instead of the problem.

And since I found the router folder and routes, this is not a SPA project? I thought I could use <a href> to link to other .vue files but I didn't know how, maybe is because if I want to do a non-SPA web I need to stick with html files and in <script> put a little bit of Vue JS

**Comment by kitwon** [comment]
Router is an option when you use cli to generte your project. You can pass false to cancel it.

Why keep router because it is one way to manage component. For example, my project has two pages `localhost:8080/index1.html` and `localhost:8080/index2.html`, but i also want to use vue-router in the first page, so i can use vue-router in first entry file `index1.js`.

After you run `npm run dev`, you can visit two modules `localhost:8080/modules/index.html` and `localhost:8080/modules/hello.html`. 
And run `npm run build`, you can see two html file in dist folder.
